services:
  - type: web
    name: medipol-ecommerce-final-project
    runtime: docker
    plan: free
    envVars:
      - key: spring.jpa.database-platform
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: JAVA_VERSION
        value: 17
