services:
  - type: web
    name: medipol-ecommerce-final-project
    runtime: java
    plan: free
    # --- BU İKİ SATIR EKSİK VE ÇOK ÖNEMLİ ---
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/ECommerceFinal-0.0.1-SNAPSHOT.jar"
    # -----------------------------------------
    envVars:
      - key: spring.jpa.database-platform
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: JAVA_VERSION
        value: 17